#ifndef VEHICLE_CONFIG_H
#define VEHICLE_CONFIG_H

#define PWM_PERIOD             16799U
#define PWM_MAX                15000U

#define CONTROL_PERIOD_MS      10U
#define HEADING_PERIOD_MS      30U
#define OLED_PERIOD_MS         200U
#define TELEMETRY_PERIOD_MS    100U
#define STATUS_PERIOD_MS       550U
#define BATTERY_PERIOD_MS      100U
#define COMMAND_TIMEOUT_MS     400U

#define MOTOR_SPEED_LIMIT_MPS  0.70f
#define DEFAULT_PID_KP         4000.0f
#define DEFAULT_PID_KI         800.0f
#define DEFAULT_PID_KD         0.0f

#define DEFAULT_MAX_YAW_RATE_DPS 150.0f
#define DEFAULT_YAW_KP         0.0010f
#define DEFAULT_YAW_KI         0.0020f
#define DEFAULT_YAW_KD         0.0f
#define DEFAULT_YAW_KFF        0.001205f

#define DEFAULT_HEADING_KP     4.0f
#define DEFAULT_HEADING_KD     0.30f
#define DEFAULT_HEADING_KFF    1.0f
#define DEFAULT_HEADING_MAX_RATE_DPS 80.0f
#define HEADING_CORRECTION_DEADBAND_DEG 0.50f
#define HEADING_MIN_CORRECTION_DPS 8.0f
#define HEADING_CORRECTION_RATE_GATE_DPS 5.0f

#define SQUARE_SIDE_DISTANCE_M 1.0f
#define SQUARE_DISTANCE_TOLERANCE_M 0.010f
#define SQUARE_POSITION_KP     1.2f
#define SQUARE_MIN_DRIVE_SPEED_MPS 0.040f
#define SQUARE_DRIVE_SPEED_TOLERANCE_MPS 0.025f
#define SQUARE_HEADING_TOLERANCE_DEG 1.0f
#define SQUARE_YAW_RATE_TOLERANCE_DPS 4.0f
#define SQUARE_SETTLE_MS       400U
#define SQUARE_DRIVE_TIMEOUT_MS 30000U
#define SQUARE_TURN_TIMEOUT_MS 10000U

#define YAW_INTEGRAL_LIMIT     300.0f
#define YAW_RATE_DEADBAND_DPS  0.50f
#define MPU_RETRY_PERIOD_MS    3000U
#define MPU_MAX_READ_FAILURES  10U

#define BATTERY_DIVIDER_RATIO  11.0f
#define ADC_REFERENCE_VOLTAGE  3.3f
#define ADC_FULL_SCALE         4095.0f

#define LEFT_COUNTS_PER_REV    1558.3f
#define RIGHT_COUNTS_PER_REV   1557.4f
#define LEFT_COUNTS_PER_METER  7514.0f
#define RIGHT_COUNTS_PER_METER 7263.0f

#define MPU_ADDRESS            (0x68U << 1)
#define MPU_REG_ACCEL_XOUT_H   0x3BU
#define MPU_REG_CONFIG         0x1AU
#define MPU_REG_GYRO_CONFIG    0x1BU
#define MPU_REG_ACCEL_CONFIG   0x1CU
#define MPU_REG_SMPLRT_DIV     0x19U
#define MPU_REG_PWR_MGMT_1     0x6BU
#define MPU_REG_WHO_AM_I       0x75U

#define UART_RX_BUFFER_SIZE    128U
#define UART_LINE_SIZE         64U
#define GRAY_SENSOR_CHANNELS   8U

#define GRAY_DISCARD_SAMPLES   3U
#define GRAY_AVERAGE_SAMPLES   2U
#define GRAY_CALIBRATION_SAMPLES 8U
#define GRAY_CALIBRATION_MIN_SPAN_ADC 300U
#define GRAY_NORMALIZED_MAX    1000U
#define GRAY_LINE_DARK_IS_HIGH 1U
#define GRAY_SENSOR_REVERSED   0U
#define GRAY_LINE_THRESHOLD_NORMALIZED 250U
#define GRAY_LINE_MIN_CONTRAST_NORMALIZED 120U
#define GRAY_CORNER_BLACK_DELTA_ADC 250U
#define GRAY_CORNER_BLACK_NORMALIZED 700U

#define LINE_BUTTON_DEBOUNCE_MS 30U
#define LINE_START_DELAY_MS    500U
#define LINE_SAMPLE_PERIOD_MS  20U
#define LINE_IDLE_SAMPLE_PERIOD_MS 100U
#define LINE_LOST_STOP_MS      250U
#define LINE_DEFAULT_SPEED_PERCENT 30U
#define LINE_MIN_THROTTLE_PERCENT 18
#define LINE_DIRECTION_KP      0.9f
#define LINE_DIRECTION_KD      0.5f
#define LINE_DIRECTION_KP_MAX  5.0f
#define LINE_DIRECTION_KD_MAX  10.0f
#define LINE_MAX_YAW_RATE_DPS  70.0f
#define LINE_LOST_SEARCH_YAW_DPS 45.0f
#define LINE_ERROR_FILTER_ALPHA 0.45f
#define LINE_CORNER_ACTIVE_CHANNELS 5U
#define LINE_CORNER_CONTIGUOUS_CHANNELS 5U
#define LINE_CORNER_CONFIRM_SAMPLES 3U
#define LINE_CORNER_BEEP_MS     500U
#define LINE_CORNER_ADVANCE_DISTANCE_M 0.090f
#define LINE_CORNER_ADVANCE_MIN_MM 10U
#define LINE_CORNER_ADVANCE_MAX_MM 1000U
#define LINE_CORNER_ADVANCE_THROTTLE_PERCENT 20
#define LINE_CORNER_ADVANCE_TIMEOUT_MS 1500U
#define LINE_CORNER_ADVANCE_TIMEOUT_PER_MM_MS 10U
#define LINE_CORNER_TURN_DEG   60.0f
#define LINE_CORNER_TURN_MIN_DEG 10U
#define LINE_CORNER_TURN_MAX_DEG 180U
#define LINE_CORNER_HEADING_TOLERANCE_DEG 1.5f
#define LINE_CORNER_YAW_RATE_TOLERANCE_DPS 5.0f
#define LINE_CORNER_SETTLE_MS  200U
#define LINE_CORNER_TURN_TIMEOUT_MS 7000U
#define LINE_CORNER_COOLDOWN_MS 800U
#define LINE_CORNER_EXIT_TIMEOUT_MS 1500U

#endif
