#ifndef VEHICLE_CONFIG_H
#define VEHICLE_CONFIG_H

#define PWM_PERIOD             16799U
#define PWM_MAX                15000U

#define CONTROL_PERIOD_MS      10U
#define HEADING_PERIOD_MS      30U
#define OLED_PERIOD_MS         200U
#define TELEMETRY_PERIOD_MS    100U
#define STATUS_PERIOD_MS       550U
#define BATTERY_PERIOD_MS      100U
#define COMMAND_TIMEOUT_MS     400U

#define DEFAULT_MAX_SPEED_MPS  0.20f
#define DEFAULT_PID_KP         4000.0f
#define DEFAULT_PID_KI         800.0f
#define DEFAULT_PID_KD         0.0f

#define DEFAULT_MAX_YAW_RATE_DPS 150.0f
#define DEFAULT_YAW_KP         0.0010f
#define DEFAULT_YAW_KI         0.0020f
#define DEFAULT_YAW_KD         0.0f
#define DEFAULT_YAW_KFF        0.001205f

#define DEFAULT_HEADING_KP     4.0f
#define DEFAULT_HEADING_KD     0.30f
#define DEFAULT_HEADING_KFF    1.0f
#define DEFAULT_HEADING_MAX_RATE_DPS 80.0f
#define HEADING_CORRECTION_DEADBAND_DEG 0.50f
#define HEADING_MIN_CORRECTION_DPS 8.0f
#define HEADING_CORRECTION_RATE_GATE_DPS 5.0f

#define SQUARE_SIDE_DISTANCE_M 1.0f
#define SQUARE_DISTANCE_TOLERANCE_M 0.010f
#define SQUARE_POSITION_KP     1.2f
#define SQUARE_MIN_DRIVE_SPEED_MPS 0.040f
#define SQUARE_DRIVE_SPEED_TOLERANCE_MPS 0.025f
#define SQUARE_HEADING_TOLERANCE_DEG 1.0f
#define SQUARE_YAW_RATE_TOLERANCE_DPS 4.0f
#define SQUARE_SETTLE_MS       400U
#define SQUARE_DRIVE_TIMEOUT_MS 30000U
#define SQUARE_TURN_TIMEOUT_MS 10000U

#define YAW_INTEGRAL_LIMIT     300.0f
#define YAW_RATE_DEADBAND_DPS  0.50f
#define MPU_RETRY_PERIOD_MS    3000U
#define MPU_MAX_READ_FAILURES  10U

#define BATTERY_DIVIDER_RATIO  11.0f
#define ADC_REFERENCE_VOLTAGE  3.3f
#define ADC_FULL_SCALE         4095.0f

#define LEFT_COUNTS_PER_REV    1558.3f
#define RIGHT_COUNTS_PER_REV   1557.4f
#define LEFT_COUNTS_PER_METER  7514.0f
#define RIGHT_COUNTS_PER_METER 7263.0f

#define MPU_ADDRESS            (0x68U << 1)
#define MPU_REG_ACCEL_XOUT_H   0x3BU
#define MPU_REG_CONFIG         0x1AU
#define MPU_REG_GYRO_CONFIG    0x1BU
#define MPU_REG_ACCEL_CONFIG   0x1CU
#define MPU_REG_SMPLRT_DIV     0x19U
#define MPU_REG_PWR_MGMT_1     0x6BU
#define MPU_REG_WHO_AM_I       0x75U

#define UART_RX_BUFFER_SIZE    128U
#define UART_LINE_SIZE         64U
#define GRAY_SENSOR_CHANNELS   8U

#endif
