DATAS SEGMENT
    SEG_TABLE DB 3FH, 06H, 5BH, 4FH, 66H, 6DH, 7DH, 07H, 7FH, 6FH
    TEST_NUM  DB 7    
DATAS ENDS
CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
    
    MOV AX, DATAS
    MOV DS, AX

    MOV AL, TEST_NUM 
    LEA BX, SEG_TABLE 
    XLAT              
    MOV DL, AL        
    
    MOV AH, 4CH
    INT 21H
CODES ENDS
END START

